In [83]:
import torch
import numpy as np

x = torch.tensor(3.0)
x
X = torch.arange(3)
print(X.size())
print(len(X))

x = torch.arange(10).reshape(5,-1)
print(x)
print(x.data_ptr())
x = x.T
print(x)
print(x.data_ptr())


torch.Size([3])
3
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
104726206893184
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])
104726206893184


Sum and cumulative sum

In [59]:
x = torch.arange(2 * 3 * 4).reshape(2, 3, 4)
print(x)
print(x.sum(axis = 0))
print(x.sum(axis = 1))
print(x.sum(axis = 2))

sum_x = x.sum(axis = 0, keepdim=True)
print(sum_x)
print(sum_x.shape)
cumsum_x = x.cumsum(axis = 2)
print(cumsum_x)
print(cumsum_x.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
tensor([[ 6, 22, 38],
        [54, 70, 86]])
tensor([[[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]])
torch.Size([1, 3, 4])
tensor([[[ 0,  1,  3,  6],
         [ 4,  9, 15, 22],
         [ 8, 17, 27, 38]],

        [[12, 25, 39, 54],
         [16, 33, 51, 70],
         [20, 41, 63, 86]]])
torch.Size([2, 3, 4])


Dot product

In [89]:
ones = torch.randn(9, dtype = torch.float32)
print(ones)
a = torch.arange(9, dtype = torch.float32)
print(a)
print(torch.dot(a,ones))
print(torch.dot(ones,a))
print((a*ones).sum())

dim0 = 5
dim1 = 4
matrix_a = torch.randn(dim0 * dim1).reshape(dim0, dim1)
vector = torch.randn(dim1)
print(torch.mv(matrix_a, vector))
matrix_b = torch.randn(dim1 * dim0).reshape(dim1, dim0)
print(torch.mm(matrix_a, matrix_b))

print(np.sqrt((matrix_a**2).sum()))
print(torch.norm(matrix_a))

tensor([ 0.4393, -0.0952,  0.8957, -1.2869, -0.2027, -0.2805,  0.7359, -0.2966,
         1.5307])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])
tensor(10.2071)
tensor(10.2071)
tensor(10.2071)
tensor([ 0.2097, -0.4983, -0.1059,  1.0584,  0.1606])
tensor([[ 1.1242,  1.0915, -1.4524,  1.0214,  2.2408],
        [-1.3609, -1.6346,  0.3532, -1.1925,  1.3929],
        [ 1.1416,  2.3039, -1.3917,  1.1645,  3.0069],
        [ 0.5770,  2.5017, -1.2431, -2.0219, -1.1712],
        [ 0.3066, -0.1573,  0.4138,  0.5578, -1.5461]])
tensor(4.0647)
tensor(4.0647)


/tmp/ipykernel_71178/2688558667.py:17: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.sqrt((matrix_a**2).sum()))


In [ ]:
dim_0 = 5
dim_1 = 6

A = torch.ones(dim_0 * dim_1).reshape(dim_0, dim_1)
print(A)
print(A.sum(axis=1, keepdim = True))
print(A / A.sum(axis=1, keepdim = True))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[6.],
        [6.],
        [6.],
        [6.],
        [6.]])
tensor([[0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]])


In [96]:
dim_0 = 5
dim_1 = 6
dim_2 = 7

A = torch.ones(dim_0 * dim_1 *dim_2).reshape(dim_0, dim_1, dim_2)

print(np.sqrt((A**2).sum()))
print(torch.norm(A))

tensor(14.4914)
tensor(14.4914)


/tmp/ipykernel_71178/1569619609.py:7: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.sqrt((A**2).sum()))


1. Consider three large matrices, say $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{14}}$, initialized with Gaussian random variables. You want to compute the product $\mathbf{A} \mathbf{B} \mathbf{C}$. Is there any difference in memory footprint and speed, depending on whether you compute $(\mathbf{A} \mathbf{B}) \mathbf{C}$ or $\mathbf{A} (\mathbf{B} \mathbf{C})$? Why?
1. Consider three large matrices, say $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{16}}$. Is there any difference in speed depending on whether you compute $\mathbf{A} \mathbf{B}$ or $\mathbf{A} \mathbf{C}^\top$? Why? What changes if you initialize $\mathbf{C} = \mathbf{B}^\top$ without cloning memory? Why?
1. Consider three matrices, say $\mathbf{A}, \mathbf{B}, \mathbf{C} \in \mathbb{R}^{100 \times 200}$. Construct a tensor with three axes by stacking $[\mathbf{A}, \mathbf{B}, \mathbf{C}]$. What is the dimensionality? Slice out the second coordinate of the third axis to recover $\mathbf{B}$. Check that your answer is correct.

1. 
I gusse it will need same amount calculation but diff in memory allocate.
When do A procuct B, will do 2^10 * 2^5 * 2^16 * 2^16 time multiplaction, allcaoting 2^10 * 2^5 memory.  
(AB) product C, will do 2^10 * 2^14 * 2^5 * 2^5 multiplaction, allcaoation 2^10 * 2^14 memory.
140754668224512 multiplaction in toal.

When do B product C, will do 2**16 * 2**14 * 2**5 * 2**5 time multiplaction, allocation 2**16 * 2**14 memory.
A(BC) will d0 2**10 * 2**14 * 2**16 * 2**16 times multiplaction
72058693549555712 multiplaction in total

2. The AC.T do faster. When doing A@B need read rows of A and colums of B each time.  
For C.T we didn't change the order of elements in memory but just the indexing.  
When doing A@C.T the columns for C.t is actually in continueous memory. Which will be faster got the GPU calcualting character.

In [105]:
import time
A = torch.randn( (2 ** 10, 2 ** 16) )
B = torch.randn( (2 ** 16, 2 ** 5) )
C = torch.randn( (2 ** 5, 2 ** 16) )

start = time.time()
A @ B
end = time.time()
print("time spent", end - start)
start = time.time()

start = time.time()
A @ C.T
end = time.time()
print("time spent", end - start)

C = B.T
print(C.data_ptr())
print(B.data_ptr())
print(C.data_ptr() == B.data_ptr())
start = time.time()
A @ C.T
end = time.time()
print("time spent", end - start)
start = time.time()

time spent 0.015203714370727539
time spent 0.017697572708129883
104726218609792
104726218609792
True
time spent 0.0168304443359375


Both (AB) and (AC^T) require the same number of floating-point operations because the matrix dimensions are identical. If (B) and (C) are independent matrices initialized separately, high-performance libraries such as BLAS or cuBLAS can efficiently handle transposed operands, so their execution times are usually very similar.

If (C = B^T) is created **without cloning memory**, then (C) is only a transposed **view** of (B). It shares the same underlying storage but has different strides. Consequently,

[
C^T = B,
]

so computing (A C^T) is effectively the same as computing (AB), without creating an additional copy of the matrix. This reduces memory usage and avoids the cost of copying data. The transpose operation itself is essentially free because it only changes the tensor's metadata (shape and strides), not the underlying data.
