In [1]:
import numpy as np
import torch


In [2]:
x = torch.arange(10, dtype=torch.float32)
print(x)
print(x.shape)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([10])


The tenser can understand as store element with start pointer, tenser shape and tensor stripe.  
For example[2, 5] tensor. The stripe would be (5, 1). The element will indexing as:  
  x[1, 3]  
= 1 * 5 + 3 * 1  
The 8th element.  

In [3]:
x = x.reshape(2, 5)
print(x)
print(x.shape)
print(x.stride())

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
torch.Size([2, 5])
(5, 1)


The torch allocate memory contineous for new tensor.  
But when .T (x = x.T), The transpos thensor will reuse the memory. Then the memory is incontineous.  
Reshape may or maynot be contineous. Need check if needed.  
The GPU operations are optimized for contineous memory.   

In [4]:
x = torch.randn(5, 4, dtype=torch.float32)
print(x)
x_ptr = x.data_ptr()
print("Array start adress",x_ptr)

tensor([[-1.1463, -0.3306, -2.2221, -0.1208],
        [ 0.7572, -2.1046, -1.4281, -1.1540],
        [ 0.1233,  1.3459, -1.9595, -0.1787],
        [-0.0855, -1.7337, -1.1364,  0.7829],
        [ 0.2807,  1.5311,  0.6628, -1.2139]])
Array start adress 100612206438528


The addresss of element in row 0

In [5]:
for i in range(x.size(1)):
    print(x[0,i].data_ptr())

100612206438528
100612206438532
100612206438536
100612206438540


The address of element in col 0

In [6]:
for i in range(x.size(0)):
    print(x[i,0].data_ptr())

100612206438528
100612206438544
100612206438560
100612206438576
100612206438592


In [7]:
x = x.reshape(1, -1)
print(x)
for i in range(x.numel()):
    print(x[0, i].data_ptr())

tensor([[-1.1463, -0.3306, -2.2221, -0.1208,  0.7572, -2.1046, -1.4281, -1.1540,
          0.1233,  1.3459, -1.9595, -0.1787, -0.0855, -1.7337, -1.1364,  0.7829,
          0.2807,  1.5311,  0.6628, -1.2139]])
100612206438528
100612206438532
100612206438536
100612206438540
100612206438544
100612206438548
100612206438552
100612206438556
100612206438560
100612206438564
100612206438568
100612206438572
100612206438576
100612206438580
100612206438584
100612206438588
100612206438592
100612206438596
100612206438600
100612206438604


In [14]:
x = torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
print(x)

y = torch.randn(3, 3)

print(torch.cat((x, y),dim=0))
print(torch.cat((y, x),dim=0))
print(torch.cat((x,y),dim=1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[ 0.0000,  1.0000,  2.0000],
        [ 3.0000,  4.0000,  5.0000],
        [ 6.0000,  7.0000,  8.0000],
        [ 0.0955, -0.4277, -1.1535],
        [-1.6234,  0.7530, -1.4561],
        [ 1.5919,  0.1054, -0.0248]])
tensor([[ 0.0955, -0.4277, -1.1535],
        [-1.6234,  0.7530, -1.4561],
        [ 1.5919,  0.1054, -0.0248],
        [ 0.0000,  1.0000,  2.0000],
        [ 3.0000,  4.0000,  5.0000],
        [ 6.0000,  7.0000,  8.0000]])
tensor([[ 0.0000,  1.0000,  2.0000,  0.0955, -0.4277, -1.1535],
        [ 3.0000,  4.0000,  5.0000, -1.6234,  0.7530, -1.4561],
        [ 6.0000,  7.0000,  8.0000,  1.5919,  0.1054, -0.0248]])


In [25]:
a = torch.arange(4).reshape(2,2)
b = torch.arange(2).reshape(1,2)
c = torch.arange(2).reshape(2,1)

print(a + b)
print(a + c)


tensor([[0, 2],
        [2, 4]])
tensor([[0, 1],
        [3, 4]])


To save memory, we would want to the tense still using the same memory after operation.

In [31]:
address = id(a)
print("address before operstion:",address)
a = a + b
print("address after operstion:",id(a))

address = id(a)
print("address before operstion:",address)
a += b
print("address after operstion:",id(a))

address = id(a)
print("address before operstion:",address)
a[:] = a + b
print("address after operstion:",id(a))



address before operstion: 124489282839616
address after operstion: 124489282831456
address before operstion: 124489282831456
address after operstion: 124489282831456
address before operstion: 124489282831456
address after operstion: 124489282831456


In [ ]:
X = torch.tensor([[0,1,2],[3,4,5]])
Y = torch.tensor([[1,1,2],[3,6,7]])
print(X == Y)
X = torch.arange(6).reshape(2,3)
Y = torch.arange(6).reshape(2,3)
print(X == Y)

tensor([[False,  True,  True],
        [ True, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor(6)
